language: r
cache: packages

before_script:
  # Dependencies are defined in DESCRIPTION
  devtools::install_github("r-quantities/units", args='--configure-args="--with-udunits2-lib=/opt/lib --with-udunits2-include=/opt/include"')

script:
  - Rscript -e "rmarkdown::render_site(input = 'src', encoding = 'UTF-8')"

deploy:
  provider: pages
  local_dir: _site
  skip_cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
