language: r
cache: packages

before_install:
  - "docker pull ubuntu:16.04"
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable -y
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install libgdal-dev libgeos-dev libproj-dev libudunits2-dev libv8-dev libprotobuf-dev protobuf-compiler libjq-dev

before_script:
  # Dependencies are defined in DESCRIPTION

script:
  - Rscript -e "rmarkdown::render_site(input = 'src', encoding = 'UTF-8')"

deploy:
  provider: pages
  local_dir: _site
  skip_cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
